/*
 * CargoNameQuantityArgumentDisplay.java
 *
 * Created on October 14, 2005, 10:14 PM
 */

package campaigneditor.display;

import campaigneditor.arguments.Argument;
import campaigneditor.arguments.CargoNameQuantityArgument;
import campaigneditor.arguments.StringArgument;

/**
 *
 * @author  Daniel Aleksandrow
 */
public class CargoNameQuantityArgumentDisplay extends ArgumentDisplay
{
    private CargoNameQuantityArgument argument;
    private ArgumentDisplay[] displaylist = {new CargoArgumentDisplay(), new IntegerArgumentDisplay(), new BooleanArgumentDisplay()};
    /** Creates new form CargoNameQuantityArgumentDisplay */
    public CargoNameQuantityArgumentDisplay(CargoNameQuantityArgument argument)
    {
        this.argument = argument;
        initialiseDisplay();
    }
    public CargoNameQuantityArgumentDisplay()
    {
        this.argument = new CargoNameQuantityArgument("Cargo Shipment");
        initialiseDisplay();
    }
    private void initialiseDisplay()
    {
        initComponents();
        reinitialiseDisplay();
    }
    private void reinitialiseDisplay()
    {
        this.removeAll();
        this.displaylist[0].setArgument(this.argument.getCargo());
        this.displaylist[1].setArgument(this.argument.getQuantity());
        this.displaylist[2].setArgument(this.argument.getMissionCargo());
        this.add(displaylist[0]);
        this.add(displaylist[1]);
        this.add(displaylist[2]);
    }
    public Argument getArgument()
    {
        return this.argument;
    }
    public void updateDisplay()
    {
        this.reinitialiseDisplay();
    }
    public void updateArgument()
    {
        this.displaylist[0].updateArgument();
        this.displaylist[1].updateArgument();
        this.displaylist[2].updateArgument();
    }
    public void setArgument(Argument argument)
    {
        CargoNameQuantityArgument newarg = (CargoNameQuantityArgument) argument;
        this.argument = newarg;
        reinitialiseDisplay();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
