/*
 * CargoMissionDisplay.java
 *
 * Created on 22 July 2005, 18:03
 */

package campaigneditor.display;

import javax.swing.JFrame;
import campaigneditor.*;

/**
 *
 * @author  Daniel Aleksandrow
 */
public class CargoMissionDisplay extends JFrame {
    
    /** Creates new form CargoMissionDisplay */
    public CargoMissionDisplay(CampaignNode node)
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        setLayout(new java.awt.BorderLayout());
        
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
