/*
 * CargoArgumentDisplay.java
 *
 * Created on October 15, 2005, 12:31 PM
 */

package campaigneditor.display;

import campaigneditor.arguments.Argument;
import campaigneditor.arguments.CargoArgument;

/**
 *
 * @author  Daniel Aleksandrow
 */
public class CargoArgumentDisplay extends ArgumentDisplay {
    private CargoArgument argument;
    /** Creates new form CargoArgumentDisplay */
    public CargoArgumentDisplay(CargoArgument argument)
    {
        this.argument = argument;
        initialiseDisplay();
    }
    public CargoArgumentDisplay()
    {
        this.argument = new CargoArgument("Cargo");
        initialiseDisplay();
    }
    private void initialiseDisplay()
    {
        initComponents();
        reinitialiseDisplay();
    }
    private void reinitialiseDisplay()
    {
        this.jLabel1.setText(this.argument.getLabel()+" (Cargo Argument)");
        this.jTextField1.setText(this.argument.getValue());
    }
    public Argument getArgument()
    {
        return this.argument;
    }
    public void updateDisplay()
    {
        this.reinitialiseDisplay();
    }
    public void updateArgument()
    {
        this.argument.setValue(this.jTextField1.getText());
    }
    public void setArgument(Argument argument)
    {
        CargoArgument newarg = (CargoArgument) argument;
        this.argument = newarg;
        reinitialiseDisplay();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("jLabel1");
        add(jLabel1);

        jTextField1.setText("jTextField1");
        add(jTextField1);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
