/*
 * IntegerArgumentDisplay.java
 *
 * Created on October 15, 2005, 12:07 PM
 */

package campaigneditor.display;

import campaigneditor.arguments.Argument;
import campaigneditor.arguments.IntegerArgument;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  Daniel Aleksandrow
 */
public class IntegerArgumentDisplay extends ArgumentDisplay {
    private IntegerArgument argument;
    /** Creates new form IntegerArgumentDisplay */
    public IntegerArgumentDisplay(IntegerArgument argument) {
        this.argument = argument;
        initComponents();
    }
    public IntegerArgumentDisplay()
    {
        this.argument = new IntegerArgument("Integer");
        initialiseDisplay();
    }
    private void initialiseDisplay()
    {
        initComponents();
        reinitialiseDisplay();
    }
    private void reinitialiseDisplay()
    {
        this.jLabel1.setText(this.argument.getLabel()+" (Integer Argument)");
        this.jSpinner1.setModel(new SpinnerNumberModel(new Integer(this.argument.getValue()), new Integer(0), null, new Integer(1)));
    }
    public Argument getArgument()
    {
        return this.argument;
    }
    public void updateDisplay()
    {
        this.reinitialiseDisplay();
    }
    public void updateArgument()
    {
        this.argument.setValue(((Integer) this.jSpinner1.getModel().getValue()).intValue());
    }
    public void setArgument(Argument argument)
    {
        IntegerArgument newarg = (IntegerArgument) argument;
        this.argument = newarg;
        reinitialiseDisplay();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        add(jSpinner1);

        jLabel1.setText("jLabel1");
        add(jLabel1);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
    
}
