/*
 * MainFrameDisplay.java
 *
 * Created on December 2, 2006, 11:27 PM
 */

package campaigneditor.display;

import campaigneditor.Campaign;
import campaigneditor.CampaignXmlIO;
import java.awt.Dimension;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

/**
 *
 * @author  daniel
 */
public class MainFrameDisplay extends javax.swing.JFrame {

    private CampaignTreeDisplay campaigntreedisplay;
    private static String LABELTEXT = "Label Count: ";
    private static String DISPLAYTITLE = "Vega Strike Campaign Editor";

    /**
     * Creates new form MainDisplay
     */
    public MainFrameDisplay() {
    
        this.setTitle(this.DISPLAYTITLE);
        campaigntreedisplay = new CampaignTreeDisplay(this);
        campaigntreedisplay.setCampaign(new Campaign());
        
        initComponents();
        
        this.campaignPane.addTab("Campaign",campaigntreedisplay);
        this.pack();
    }
    
    public void showCampaignNode(CampaignNodeDisplay displaycn)
    {
//        JFrame framecn = new JFrame();
//        framecn.setMaximumSize(new Dimension(500,300));
//        framecn.add(displaycn);
//        framecn.setTitle("blah");
//        framecn.pack();
//        framecn.setVisible(true);
        this.splitPane.setRightComponent(displaycn);
    }
    public void hideCampaignNode()
    {
        this.splitPane.setRightComponent(this.edittingPane);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        newButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        mainTitle = new javax.swing.JLabel();
        splitPane = new javax.swing.JSplitPane();
        edittingPane = new javax.swing.JPanel();
        campaignPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campaigneditor/resources/campaign-new.png")));
        newButton.setText("New");
        newButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newButtonMouseClicked(evt);
            }
        });

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campaigneditor/resources/campaign-open.png")));
        openButton.setText("Open");
        openButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openButtonMouseClicked(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campaigneditor/resources/campaign-save.png")));
        saveButton.setText("Save");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        mainTitle.setFont(new java.awt.Font("Lucida Grande", 2, 12));
        mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainTitle.setText("CampaignEditor  . version 0.02");
        mainTitle.setEnabled(false);

        splitPane.setContinuousLayout(true);
        edittingPane.setMinimumSize(new java.awt.Dimension(720, 600));
        edittingPane.setPreferredSize(new java.awt.Dimension(600, 400));
        GroupLayout edittingPaneLayout = new GroupLayout(edittingPane);
        edittingPane.setLayout(edittingPaneLayout);
        edittingPaneLayout.setHorizontalGroup(
            edittingPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        edittingPaneLayout.setVerticalGroup(
            edittingPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        splitPane.setRightComponent(edittingPane);

        campaignPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        splitPane.setLeftComponent(campaignPane);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(newButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(mainTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(splitPane, GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(newButton)
                        .addComponent(openButton)
                        .addComponent(saveButton))
                    .addComponent(mainTitle))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPane, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        System.out.print("Generating XML ..");
        Document campaignXML = this.campaigntreedisplay.getCampaign().toXml();
        System.out.print(". generated.");
        final JFileChooser fc = new JFileChooser();
        int returned = fc.showSaveDialog(this);
        
        if (returned != JFileChooser.APPROVE_OPTION) {
            return;
        }
        CampaignXmlIO.writeXmlFile(campaignXML,fc.getSelectedFile());
        return;
    }//GEN-LAST:event_saveButtonMouseClicked

    private void openButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openButtonMouseClicked
        final JFileChooser fc = new JFileChooser();
        int returned = fc.showOpenDialog(this);
        
        if (returned != JFileChooser.APPROVE_OPTION) {
            return;
        }
        Document save = CampaignXmlIO.readXmlFile(fc.getSelectedFile());
        NodeList campaignElements = save.getElementsByTagName("CampaignData").item(0).getChildNodes();
        Campaign newcampaign;
        NodeList nodes;
        for (int i = 0 ; i < campaignElements.getLength() ; i++) {
            if (campaignElements.item(i).getNodeType() == Node.ELEMENT_NODE) {
                newcampaign = new Campaign(campaignElements.item(i).getAttributes().getNamedItem("name").getNodeValue());
                nodes = campaignElements.item(i).getChildNodes();
                for (int j = 0 ; j < nodes.getLength() ; j++) {
                    newcampaign.addNode(nodes.item(j));
                }
                this.campaigntreedisplay.setCampaign(newcampaign);
                break;
            }
        }
        this.pack();
        return;
    }//GEN-LAST:event_openButtonMouseClicked

    private void newButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newButtonMouseClicked
        Object selectedValue;
        selectedValue = JOptionPane.showInputDialog(null,
                "Enter a name for the new campaign.", "Campaign Name",
                JOptionPane.INFORMATION_MESSAGE, null,
                null, Campaign.GENERICCAMPAIGNNAME);
        String campaignname = (String) selectedValue;
        if ((campaignname != null) && (campaignname.length() > 0))//value is valid
        {
            this.campaigntreedisplay.setCampaign(new Campaign(campaignname));
            
        }
    }//GEN-LAST:event_newButtonMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameDisplay().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane campaignPane;
    private javax.swing.JPanel edittingPane;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
    
}
