/*
 * SpeechArgumentDisplay.java
 *
 * Created on February 15, 2007, 9:45 PM
 */

package campaigneditor.display;

import campaigneditor.arguments.Argument;
import campaigneditor.arguments.SpeechArgument;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

/**
 *
 * @author  daniel
 */
public class SpeechArgumentDisplay extends ArgumentDisplay {
    private SpeechArgument argument;
    private ArrayList displaylist = new ArrayList();
    /**
     * Creates new form SpeechArgumentDisplay
     */
    public SpeechArgumentDisplay(SpeechArgument argument) {
        this.argument = argument;
        initComponents();
        this.updateDisplay();
    }
    public SpeechArgumentDisplay() {
        initComponents();
    }
    
    public Argument getArgument()
    {
        return this.argument;
    }
    public void setArgument(Argument a)
    {
        this.argument = (SpeechArgument) a;
        this.updateDisplay();
    }
    public void updateArgument()
    {
        Component[] displayarray = this.speechPanel.getComponents();
        String[][] rowarray = new String[displayarray.length][2];
        for (int i = 0 ; i < displayarray.length ; i++)
        {
            rowarray[i] = ((SpeechArgumentRowDisplay) this.displaylist.get(i)).getDisplay();
        }
        this.argument.setValue(rowarray);
        return;
    }
    
    public void updateDisplay()
    {
        this.speechPanel.setVisible(false);
        SpeechArgumentRowDisplay newrow;
        for (String[] line : this.argument.getValue())
        {
            newrow = this.addNewRow();
            newrow.updateDisplay(line);
        }
        this.speechPanel.setVisible(true);
    }
    
    private SpeechArgumentRowDisplay getSelected()
    {
        SpeechArgumentRowDisplay speechrow;
        for (Component row : this.speechPanel.getComponents())
        {
            speechrow = (SpeechArgumentRowDisplay) row;
            if (speechrow.isSelected())
            {
                return speechrow;
            }
        }
        return null;
    }
    
    private SpeechArgumentRowDisplay addNewRow()
    {
        SpeechArgumentRowDisplay newrow = new SpeechArgumentRowDisplay();
        this.speechPanel.add(newrow);
        this.displaylist.add(newrow);
        return newrow;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        textArgLabel = new javax.swing.JLabel();
        addLineButton = new javax.swing.JButton();
        removeLineButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        speechPanel = new javax.swing.JPanel();

        textArgLabel.setText("Argument Label");

        addLineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campaigneditor/resources/node-new.png")));
        addLineButton.setOpaque(false);
        addLineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLineButtonMouseClicked(evt);
            }
        });

        removeLineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campaigneditor/resources/node-delete.png")));
        removeLineButton.setOpaque(false);
        removeLineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeLineButtonMouseClicked(evt);
            }
        });

        speechPanel.setLayout(new javax.swing.BoxLayout(speechPanel, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setViewportView(speechPanel);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(textArgLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(addLineButton, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeLineButton, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)))
                .addGap(276, 276, 276))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textArgLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(removeLineButton, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLineButton, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeLineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeLineButtonMouseClicked
        SpeechArgumentRowDisplay speechrow = this.getSelected();
        if (speechrow != null)
        {
            this.speechPanel.remove(speechrow);
            this.displaylist.remove(speechrow);
        }
    }//GEN-LAST:event_removeLineButtonMouseClicked

    private void addLineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLineButtonMouseClicked
        
        this.addNewRow();

    }//GEN-LAST:event_addLineButtonMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLineButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeLineButton;
    private javax.swing.JPanel speechPanel;
    private javax.swing.JLabel textArgLabel;
    // End of variables declaration//GEN-END:variables
    
}
