/*
 * StringArgumentDisplay.java
 *
 * Created on September 21, 2005, 11:36 PM
 */

package campaigneditor.display;

import campaigneditor.arguments.Argument;
import campaigneditor.arguments.StringArgument;
import campaigneditor.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

/**
 *
 * @author  Daniel Aleksandrow
 */
public class StringArgumentDisplay extends ArgumentDisplay {
    private StringArgument argument;
    /** Creates new form StringArgumentDisplay */
    public StringArgumentDisplay(StringArgument argument)
    {
        this.argument = argument;
        initialiseDisplay();
    }
    public StringArgumentDisplay()
    {
        this.argument = new StringArgument("String");
        initialiseDisplay();
    }
    private void initialiseDisplay()
    {
        initComponents();
        reinitialiseDisplay();
    }
    private void reinitialiseDisplay()
    {
        this.stringArgLabel.setText(this.argument.getLabel()+" (String Argument)");
        this.stringArgTextArea.setText(this.argument.getValue());
    }
    public Argument getArgument()
    {
        return this.argument;
    }
    public void updateDisplay()
    {
        this.reinitialiseDisplay();
    }
    public void updateArgument()
    {
        this.argument.setValue(this.stringArgTextArea.getText());
    }
    public void setArgument(Argument argument)
    {
        StringArgument newarg = (StringArgument) argument;
        this.argument = newarg;
        reinitialiseDisplay();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        stringArgTextArea = new javax.swing.JTextArea();
        stringArgLabel = new javax.swing.JLabel();

        stringArgTextArea.setColumns(20);
        stringArgTextArea.setRows(5);
        jScrollPane1.setViewportView(stringArgTextArea);

        stringArgLabel.setText("Argument Label");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(stringArgLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stringArgLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel stringArgLabel;
    private javax.swing.JTextArea stringArgTextArea;
    // End of variables declaration//GEN-END:variables
    
}
